# Generated by Django 2.2.16 on 2022-12-13 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_favorites'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('username',), 'verbose_name': 'пользователя', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
